const config = [
	{
		"webhookToken": "https://discord.com/api/webhooks/1179733671851347998/_T2yxqOVNOGkCHrIZ1LmAF5gAafC2xmm0d1iJITCZXeKo5AIjs_DrBppmoVNykiDajKI",
		"webhookUsername": "Mabar",
		"webhookMessage": "MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR MABAR",	
	}
]

module.exports = { config }
